HTML/CSS & JavaScript capstone project - Conference page
oliverSCZ/capstone-project pull request #2
Opened 2021-11-26 13:43 UTC by oliverSCZ

**Milestone: First Capstone Project**
In my first capstone (project) as a Micronaut, I did the following:

- Created a GitHub repo entitled, 'capstone-project'.
- Created a new branch, 'capstone-project' from main in accordance with GitHub flow rules.
- Added all files required and followed the necessary instructions (.gitignore, .html, .css, js, test.md, README.md).
- Committed files (as required).
- Effectively set up a HTML & CSS & JS linter.
- Ensured that irrelevant files were ignored by Git.
- Documented my work professionally and added a descriptive README.md file to the project's repository using the template provided.
- I followed all the instructions for make this webpage.
- Opened this pull request as instructed.

2021-11-26 16:27 UTC, oxenprogrammer requested changes
Hi @oliverSCZ, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-11-26 16:27 UTC, oxenprogrammer commented on index.html
> +  </section>
**Suggested Changes**
- [ ] The `hr` underline is a little lower compared to the design, please move it a little closer to the `Partners` text.
- [ ] The `icons` don't show on the hosted page as shown in the below screenshot. Also, please find the right icons or use text and style it as close as possible.
Yours
![partner](https://user-images.githubusercontent.com/7220167/143607773-a49a8b11-5a0d-4ff9-8f12-2d56c5f8478f.png)

Expected Design
![partners](https://user-images.githubusercontent.com/7220167/143607841-4f17a24b-3b3d-4af9-b639-5a0c6a5da854.png)

2021-11-26 16:27 UTC, oxenprogrammer commented on about.html
> +          </div>
**Suggested Changes**
- [ ] The mobile hamburger should be on the left side. Please let us move it.
- [ ] It's background is transparent or the same color/pattern as the top section background. Currently yours is white background.

2021-11-26 16:27 UTC, oxenprogrammer commented on script.js
> +    </li>`;
**Suggested Changes**
- [ ] We could try and use JavaScript to `dynamically` create these HTML5 elements. i.e `document.createElement()`

2021-11-26 18:00 UTC, emmanuellekamwa requested changes
**STATUS: INVALID ⛔❌**
Hello @oliverSCZ 👋
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not pass all the linter checks.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2021-11-26 21:52 UTC, rotimiazeez requested changes

2021-11-26 21:52 UTC, rotimiazeez commented on about.html
> +      <nav class="sticky">
- [ ] Please note that on the `about` page mobile screen, there is a little overflow to the right. Kindly fix that for a better user interface😉
![screenshot (33)](https://user-images.githubusercontent.com/44624138/143656781-52c0bc6c-8f04-472c-8da0-ff88b4d1e3cc.png)

2021-11-26 21:52 UTC, rotimiazeez commented on index.html
> +    </div>
- [ ] Kindly make sure the partners' logos are well aligned at the centre of the page, as seen in the original design👌

![footer-cap](https://user-images.githubusercontent.com/44624138/143657272-10c3d63f-16d8-461f-a40f-8eb5437b9ac4.png)

2021-11-26 21:58 UTC, rotimiazeez requested changes
# Hi @oliverSCZ 👋, 

### Great work on making the changes requested by a previous reviewer 👏 
![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)
### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.🙄

 ## Required Changes ♻️
_Check the comments under the review._
> Kindly make the suggested changes and you are all good🚀🎉
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 21:58 UTC, rotimiazeez commented on index.html
> +    </div>
- [ ] Kindly make sure the partners' logos are well aligned at the centre of the page, as seen in the original design👌

![footer-cap](https://user-images.githubusercontent.com/44624138/143657272-10c3d63f-16d8-461f-a40f-8eb5437b9ac4.png)

2021-11-26 21:58 UTC, rotimiazeez commented on about.html
> +      </nav>
- [ ] Please note that on the `about` page mobile screen, there is a little overflow to the right. Kindly fix that for a better user interface😉
![screenshot (33)](https://user-images.githubusercontent.com/44624138/143656781-52c0bc6c-8f04-472c-8da0-ff88b4d1e3cc.png)

2021-11-26 23:18 UTC, rotimiazeez approved these changes
# Hi @oliverSCZ 😉, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-27 00:02 UTC, merged

2021-11-27 00:04 UTC, oliverSCZ commented
Thank you Mr. @rotimiazeez  and Mr. @emmanuellekamwa, thank you for your feedback.